import { Article, VocabWord } from '@/types';

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Smartphones May Soon Last a Week Per Charge',
    imageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600',
    topic: 'Technology', topicId: 'technology', topicColor: '#3B82F6',
    difficulty: 'Beginner', readTime: 5, publishedAt: '1 hour ago',
    content: 'Researchers have made a breakthrough in battery technology...',
    source: 'The Guardian', recommended: true,
  },
  {
    id: '2',
    title: 'Tech Giants Invest in Renewable Energy',
    imageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600',
    topic: 'Technology', topicId: 'technology', topicColor: '#3B82F6',
    difficulty: 'Intermediate', readTime: 2, publishedAt: '1 day ago',
    content: 'Major technology companies are pledging billions toward renewable energy...',
    source: 'BBC News', recommended: true,
  },
  {
    id: '3',
    title: 'Extreme Sports Gain Olympic Recognition',
    imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=600',
    topic: 'Sports', topicId: 'sports', topicColor: '#10B981',
    difficulty: 'Beginner', readTime: 3, publishedAt: '2 hours ago',
    content: 'The International Olympic Committee has announced new extreme sports categories...',
    source: 'The Guardian', likedByFriends: ['@ashleynam'],
  },
  {
    id: '4',
    title: 'Cybersecurity Threats Rise in Digital Age',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600',
    topic: 'Technology', topicId: 'technology', topicColor: '#3B82F6',
    difficulty: 'Intermediate', readTime: 4, publishedAt: '5 hours ago',
    content: 'New cybersecurity reports indicate a 40% rise in ransomware attacks...',
    source: 'Reuters', trending: true,
  },
  {
    id: '5',
    title: 'VR Headsets Become More Affordable',
    imageUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=600',
    topic: 'Technology', topicId: 'technology', topicColor: '#3B82F6',
    difficulty: 'Intermediate', readTime: 3, publishedAt: '3 hours ago',
    content: 'The price of virtual reality headsets has dropped significantly...',
    source: 'The Verge', likedByFriends: ['@shreyask'],
  },
  {
    id: '6',
    title: 'Plant-Based Diets Linked to Longer Life',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600',
    topic: 'Health & Fitness', topicId: 'health', topicColor: '#EF4444',
    difficulty: 'Beginner', readTime: 4, publishedAt: '6 hours ago',
    content: 'A comprehensive study shows that plant-based diets can extend life expectancy...',
    source: 'The Guardian', recommended: true,
  },
  {
    id: '7',
    title: 'NASA Discovers Water on the Moon',
    imageUrl: 'https://images.unsplash.com/photo-1446776899648-aa78eefe8ed0?w=600',
    topic: 'Science', topicId: 'science', topicColor: '#06B6D4',
    difficulty: 'Intermediate', readTime: 6, publishedAt: '2 days ago',
    content: 'NASA scientists have confirmed the presence of water ice...',
    source: 'Reuters', trending: true,
  },
  {
    id: '8',
    title: 'Remote Work Is Reshaping City Centers',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600',
    topic: 'Business', topicId: 'business', topicColor: '#6366F1',
    difficulty: 'Advanced', readTime: 7, publishedAt: '4 hours ago',
    content: 'The shift to remote work has had significant economic impacts on urban centers...',
    source: 'The Guardian', likedByFriends: ['@ashleynam', '@shreyask'],
  },
  {
    id: '9',
    title: 'Street Food Festivals Return Worldwide',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600',
    topic: 'Food & Cooking', topicId: 'food', topicColor: '#F59E0B',
    difficulty: 'Beginner', readTime: 2, publishedAt: '8 hours ago',
    content: 'Cities around the world are hosting street food festivals...',
    source: 'BBC News', recommended: true,
  },
  {
    id: '10',
    title: 'Electric Vehicles Hit 30% of New Car Sales',
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600',
    topic: 'Technology', topicId: 'technology', topicColor: '#3B82F6',
    difficulty: 'Intermediate', readTime: 5, publishedAt: '1 day ago',
    content: 'Electric vehicles now account for nearly a third of all new car sales globally...',
    source: 'Reuters', trending: true,
  },
];

export const MOCK_VOCAB: VocabWord[] = [
  {
    id: 'v1', word: 'breakthrough',
    definition: 'An important discovery or development',
    context: 'Researchers have made a breakthrough in battery technology',
    articleId: '1', savedAt: '2 days ago',
  },
  {
    id: 'v2', word: 'ransomware',
    definition: 'Malicious software that demands payment to restore access',
    context: 'New cybersecurity reports indicate a rise in ransomware attacks',
    articleId: '4', savedAt: '1 day ago',
  },
  {
    id: 'v3', word: 'pledging',
    definition: 'Making a formal commitment or promise',
    context: 'Major technology companies are pledging billions toward renewable energy',
    articleId: '2', savedAt: '3 days ago',
  },
];
